[package]
name = "agogo-core"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
chan_impl = { package = "agogo-chan", path = "../chan" }
connections = { workspace = true }
rtrb = { workspace = true }
rust-fsm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
chan_impl = { package = "agogo-chan", path = "../chan", features = ["testkit"] }
proptest = { workspace = true }
